import { S } from '../core/state.js';
const AMBIENT=[
 {t:"Le bulletin de l'Institut tire à quarante mille exemplaires.",y:[1930,1960]},
 {t:"Une maquette d'Atlantropa au 1/200 000 est exposée au Deutsches Museum.",y:[1930,1955]},
 {t:"Un train de ciment par heure franchit Algésiras.",c:()=>!S.built.gib&&S.prog.gib>0.2},
 {t:"On recense soixante-deux mille ouvriers sur le seul chantier de Gibraltar.",c:()=>S.active.gib},
 {t:"Le premier gigawatt atlantropéen a été livré à Séville.",c:()=>S.power>1&&S.power<12},
 {t:"Les mouettes ont déserté le port de Gênes.",c:()=>S.levelW<-8},
 {t:"Un banc de sable émerge au large de Djerba. On le baptise île Sörgel.",c:()=>S.levelW<-18},
 {t:"La température estivale à Malaga a gagné un degré depuis la fermeture du détroit.",c:()=>S.levelW<-30},
 {t:"Les vignerons du Roussillon signalent des dépôts blancs sur les feuilles.",c:()=>S.dust>10},
 {t:"Un troupeau de flamants s'est posé sur les salines nouvelles. Les ornithologues hésitent entre l'émerveillement et l'inquiétude.",c:()=>S.land>5000},
 {t:"Le prix du fret entre Marseille et Alexandrie a triplé en dix ans.",c:()=>S.deadPorts>2},
 {t:"Trois villages de pêcheurs kabyles ont été abandonnés cette année.",c:()=>S.salW>40},
 {t:"Un géographe propose de rebaptiser la Méditerranée « lac d'Atlantropa ». Personne ne suit.",c:()=>S.levelW<-50},
 {t:"La Bourse de Zurich cote pour la première fois des terrains situés à moins cent mètres.",c:()=>S.land>30000},
 {t:"Des scouts allemands traversent à pied de la Sicile à la Tunisie.",c:()=>S.built.sic},
 {t:"Le dernier phare du golfe du Lion a été éteint : il éclairait une plaine.",c:()=>S.levelW<-70},
 {t:"Un ancien pêcheur de Sète cultive des asperges sur ce qui fut son lieu de pêche. Elles ne poussent pas.",c:()=>S.land>20000},
 {t:"L'Institut compte désormais plus de juristes que d'ingénieurs.",y:[1955,2100]},
 {t:"Une compagnie aérienne propose le survol des fonds au départ de Nice.",c:()=>S.land>25000},
 {t:"Les archives de l'Institut occupent maintenant quatre kilomètres de rayonnages.",y:[1970,2100]},
 {t:"Un cargo s'est ensablé sur un haut-fond qui ne figurait sur aucune carte.",c:()=>S.levelW<-20&&S.levelW>-60},
 {t:"La pêche méditerranéenne représente désormais moins d'un pour cent des captures européennes.",c:()=>S.biodiv<45},
 {t:"Les sels de Camargue ont été déclassés : trop de magnésium.",c:()=>S.salW>40.5},
 {t:"On a retrouvé un sous-marin allemand de 1943, intact, à quatre-vingts kilomètres de la côte.",y:[1946,2100],c:()=>S.land>15000},
 {t:"Le mot « atlantropéen » entre au dictionnaire.",y:[1950,2100]},
 {t:"Un cyclone de poussière saline a traversé la plaine du Pô.",c:()=>S.dust>30},
 {t:"Les caves de Champagne signalent une hausse anormale des températures d'automne.",c:()=>S.levelW<-95},
 {t:"Un journaliste calcule que le chantier a consommé plus de béton que toutes les cathédrales d'Europe réunies.",c:()=>S.built.gib},
 {t:"L'Institut fête son centenaire. Il ne reste plus personne qui ait connu Sörgel.",y:[2028,2035]},
 {t:"Une carte d'Atlantropa est affichée dans le hall de la gare centrale de Munich. Elle est encore juste.",y:[1930,1945]}
];
export { AMBIENT };
